enabled: true
favicon: {  }
logo:
  user/themes/mache/images/logo.png:
    name: logo.png
    type: image/png
    size: 1824
    path: user/themes/mache/images/logo.png
left_footer: "&copy; 2015 COPYRIGHT MACHE TEMPLATE\n\nHébergé par Club Cédille\n"
right_footer: 'DESIGNED BY SYMU.CO'
blog_thumbnail_width: 600
blog_thumbnail_height: 450
default_background_image:
  user/themes/mache/images/freepsdanner.jpg:
    name: freepsdanner.jpg
    type: image/jpeg
    size: 53599
    path: user/themes/mache/images/freepsdanner.jpg
